### ISSUE TITLE
Multiple versions of a module

### ISSUE THREAD

**Issue by Foxite** [Quahu/Qmmands#16]
Would it be possible to add multiple versions of a module from a single class? I'm trying to add a module class multiple times, each time with a different `CultureInfo` when translating command names, but I get an exception when adding the module a second time.

**Comment by Quahu** [comment]
Hm, I've never considered anyone doing that. From experience, most people seem to instead localise the various parts of the modules on the fly, when they're requested, instead of registering already localised variants. What's stopping this behavior is a very basic check that's there to simply prevent accidentally adding the same module twice.

I understand that each module's group aliases and commands' aliases would also be translated, correct?

**Comment by Foxite** [comment]
That's correct. I also add a CheckAttribute which restricts the entire module to guilds that use that locale.

**Comment by Quahu** [comment]
With this, it'd make sense for you to localise both aliases and other information when adding the modules. It'd also be more performant this way.
